version: '3.0'

volumes:
    mysql-volume:
    pma-session-store:


services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./laravel:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel_tutorial_dev
            - DB_USERNAME=student
            - DB_PASSWORD=student

    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 82:80
        depends_on:
            - app
        volumes:
            - ./laravel:/var/www/html

    db:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: laravel_tutorial_dev
            MYSQL_USER: student
            MYSQL_PASSWORD: student
            MYSQL_ROOT_PASSWORD: root
            TZ: 'Asia/Tokyo'
        volumes:
            - mysql-volume:/var/lib/mysql

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=student
            - PMA_PASSWORD=student
        ports:
            - 8080:80
        volumes:
            - pma-session-store:/sessions